from src.config.llm_config import llm
from src.controller.nodes.prompt import final_prompt

def build_sql_query(schema, user_query):
    output_schema = {
        "name": "SQLGenerator",
        "description": "Generate a PostgreSQL query",
        "parameters": {
            "type": "object",
            "properties": {
                "generated_sql": {
                    "type": "string",
                    "description": "The SQL query generated by the model based on the user query and schema."
                }
            },
            "required": ["generated_sql"]
        }
    }

    response = llm.with_structured_output(output_schema).invoke(final_prompt.format(schema=schema, user_query=user_query))

    sql_query = response['generated_sql']

    clean_sql_query = sql_query.replace("```sql", "").replace("```", "").strip()\
    
    return clean_sql_query